import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { progress, leaderboard, monthRange, teamToday, challengePhase, daysRemaining, type Challenge, type ChallengeEntry } from '../lib/challenges';

test('progress counts accepted entries only, preserves ties and uses team calendar boundaries',()=>{
 const c={id:'c',target:10,collective_target:30,starts_on:'2026-09-01',ends_on:'2026-09-30',archived:false} as Challenge;
 const entries=[['u',8,'approved'],['u',2,'pending'],['u',6,'rejected'],['v',8,'approved'],['w',12,'approved']].map(([user_id,amount,status],i)=>({id:String(i),challenge_id:'c',user_id,amount,status})) as ChallengeEntry[];
 assert.deepEqual(progress(c,entries,'u'),{total:8,pending:2,percent:80,complete:false,target:10});
 assert.equal(progress(c,entries).total,28);assert.equal(progress(c,entries).complete,false);
 assert.equal(progress(c,entries,'w').percent,100);assert.equal(progress(c,entries,'w').complete,true);
 assert.deepEqual(leaderboard(c,['u','v','w','zero'].map(user_id=>({user_id,challenge_id:'c'})),entries).map(r=>r.rank),[1,2,2,4]);
 assert.equal(teamToday('America/Mexico_City',new Date('2026-10-01T02:00:00Z')),'2026-09-30');
 assert.deepEqual(monthRange('2028-02-15'),{starts_on:'2028-02-01',ends_on:'2028-02-29'});
 assert.equal(challengePhase(c,'2026-08-31'),'Próximamente');assert.equal(challengePhase(c,'2026-09-30'),'En marcha');assert.equal(challengePhase(c,'2026-10-01'),'Finalizado');assert.equal(daysRemaining(c,'2026-09-30'),1);
});

test('challenge database enforces membership, dates, evidence privacy, coach review and immutable rules',async()=>{
 const db=new PGlite();
 try {
  await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
   create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}');
   create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
   grant usage on schema auth,storage to authenticated,anon;
   create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
   create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
   alter table storage.objects enable row level security;grant select,insert,update,delete on storage.objects to authenticated;`);
  for(const file of ['202609210001_multiuser.sql','202609220001_member_removal.sql','202609290001_monthly_challenges.sql'])await db.exec(await readFile(new URL(`../supabase/migrations/${file}`,import.meta.url),'utf8'));
  const admin=crypto.randomUUID(),member=crypto.randomUUID(),peer=crypto.randomUUID(),outsider=crypto.randomUUID();
  for(const id of [admin,member,peer,outsider])await db.query('insert into auth.users(id) values($1)',[id]);
  const as=async(id:string)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
  const scalar=async(sql:string,args:unknown[]=[]) => (await db.query<{v:string}>(sql,args)).rows[0].v;
  await as(admin);const team=await scalar("select public.create_team('Retos') v");
  const invite=await scalar('select public.create_invite($1) v',[team]);
  const create=(metric='km',approval=true,offset=0)=>scalar("insert into public.challenges(team_id,title,metric,target,starts_on,ends_on,requires_approval) values($1,'Reto',$2,10,(now() at time zone 'America/Mexico_City')::date-2,(now() at time zone 'America/Mexico_City')::date+$4::int,$3) returning id v",[team,metric,approval,offset]);
  const c=await create(),habit=await create('habit',false),closed=await create('km',false,-1);
  for(const id of [member,peer]){await as(id);await db.query('select public.join_team($1)',[invite]);}
  const date=await scalar("select ((now() at time zone 'America/Mexico_City')::date)::text v");
  await as(member);
  await assert.rejects(create(),/row-level security/i);
  const log=(id:string,quantity=4,proof:string|null=null,challenge=c,day=date)=>db.query('select public.log_challenge_activity($1,$2,$3,$4,$5,$6)',[challenge,id,day,quantity,'Rodaje',proof]);
  await assert.rejects(log(crypto.randomUUID()),/Únete/i);
  await db.query('select public.join_challenge($1)',[c]);await db.query('select public.join_challenge($1)',[c]);
  await assert.rejects(db.query('select public.join_challenge($1)',[closed]),/cerrado/i);
  await assert.rejects(log(crypto.randomUUID(),0),/cantidad/i);
  await assert.rejects(log(crypto.randomUUID(),1.001),/cantidad/i);
  await assert.rejects(log(crypto.randomUUID(),1,null,c,'2099-01-01'),/fechas/i);
  await assert.rejects(log(crypto.randomUUID(),1,null,c,'2000-01-01'),/fechas/i);
  const entry=crypto.randomUUID(),path=`${team}/${c}/${member}/${entry}.jpg`;
  await assert.rejects(log(entry,4,path),/evidencia/i);
  await db.query("insert into storage.objects(bucket_id,name) values('challenge-evidence',$1)",[path]);
  await log(entry,4,path);await log(entry,4,path);
  assert.equal((await db.query('select * from public.challenge_entries')).rows.length,1);
  assert.equal(await scalar('select status v from public.challenge_entries where id=$1',[entry]),'pending');
  await assert.rejects(db.query("update public.challenge_entries set status='approved'"),/permission denied/i);
  await assert.rejects(db.query("select public.review_challenge_entry($1,'approved','')",[entry]),/coach/i);
  await assert.rejects(db.query("update public.challenges set target=1"),/permission denied/i);
  assert.equal((await db.query('delete from storage.objects returning id')).rows.length,0);
  await assert.rejects(log(entry,5,path),/identificador/i);
  await db.query('select public.join_challenge($1)',[habit]);
  await assert.rejects(log(crypto.randomUUID(),1.5,null,habit),/cantidad/i);
  const habitEntry=crypto.randomUUID();await log(habitEntry,1,null,habit);
  assert.equal(await scalar('select status v from public.challenge_entries where id=$1',[habitEntry]),'approved');
  await as(peer);
  assert.equal((await db.query('select * from public.challenge_entries')).rows.length,2);
  assert.equal((await db.query('select * from storage.objects')).rows.length,0);
  await assert.rejects(db.query('select public.delete_challenge_entry($1)',[entry]),/propios/i);
  await as(outsider);
  assert.equal((await db.query('select * from public.challenges')).rows.length,0);
  assert.equal((await db.query('select * from public.challenge_entries')).rows.length,0);
  await assert.rejects(db.query('select public.join_challenge($1)',[c]),/acceso/i);
  await assert.rejects(log(crypto.randomUUID()),/acceso/i);
  await as(admin);
  assert.equal((await db.query('select * from storage.objects')).rows.length,1);
  await db.query("select public.review_challenge_entry($1,'approved','Bien')",[entry]);
  assert.equal(await scalar('select status v from public.challenge_entries where id=$1',[entry]),'approved');
  await db.query("select public.review_challenge_entry($1,'rejected','Duplicado')",[entry]);
  assert.equal(await scalar('select status v from public.challenge_entries where id=$1',[entry]),'rejected');
  await db.query('select public.join_challenge($1)',[c]);const own=crypto.randomUUID();await log(own);
  await assert.rejects(db.query("select public.review_challenge_entry($1,'approved','')",[own]),/Otro coach/i);
  await db.query('select public.archive_challenge($1)',[c]);
  await as(member);await assert.rejects(log(crypto.randomUUID()),/abierto/i);
  assert.equal(await scalar('select public.delete_challenge_entry($1) v',[entry]),path);
  assert.equal((await db.query('delete from storage.objects returning id')).rows.length,1);
  await as(admin);await db.query('select public.remove_team_member($1,$2)',[team,member]);
  await as(member);assert.equal((await db.query('select * from public.challenges')).rows.length,0);
  await assert.rejects(log(crypto.randomUUID(),1,null,habit),/acceso/i);
  await db.exec('reset role;set role anon');await assert.rejects(db.query('select * from public.challenges'),/permission denied/i);
 } finally {await db.close();}
});
