import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

test('migration executes and PostgreSQL enforces multi-tenant roles, attendance and Storage policies', async () => {
 const db = new PGlite();
 try {
  // Only the platform-owned schemas are simulated. The migration and its RLS run unmodified.
  await db.exec(`create role anon; create role authenticated;
   create schema auth; create schema storage;
   create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}');
   create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
   grant usage on schema auth,storage to authenticated,anon;
   grant execute on function auth.uid() to authenticated,anon;
   create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
   create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
   alter table storage.objects enable row level security;
   grant select,insert,update,delete on storage.objects to authenticated;
  `);
  await db.exec(await readFile(new URL('../supabase/migrations/202609210001_multiuser.sql', import.meta.url),'utf8'));
  const admin='10000000-0000-0000-0000-000000000001', coach='10000000-0000-0000-0000-000000000002', member='10000000-0000-0000-0000-000000000003', outsider='10000000-0000-0000-0000-000000000004';
  for(const id of [admin,coach,member,outsider]) await db.query('insert into auth.users(id) values($1)',[id]);
  const as = async(id:string) => { await db.exec('reset role'); await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]); await db.exec('set role authenticated'); };
  const scalar = async(sql:string,params:unknown[]=[]) => (await db.query<Record<string,unknown>>(sql,params)).rows[0];
  await as(admin);
  const team = (await scalar("select public.create_team('Bestias de montaña') as id")).id as string;
  const invite = (await scalar('select public.create_invite($1) as code',[team])).code as string;
  await as(coach); await db.query('select public.join_team($1)',[invite]);
  await as(member); await db.query('select public.join_team($1)',[invite]);
  await assert.rejects(db.query("update public.memberships set role='admin' where user_id=$1",[member]), /permission denied/i);
  await assert.rejects(db.query("select public.set_member_role($1,$2,'admin')",[team,member]), /Solo administradores/);
  await assert.rejects(db.query('select public.create_invite($1)',[team]), /Solo administradores/);
  await as(admin); await db.query("select public.set_member_role($1,$2,'coach')",[team,coach]);
  await assert.rejects(db.query("select public.set_member_role($1,$2,'member')",[team,admin]),/al menos un administrador/);
  await as(outsider); const otherTeam = (await scalar("select public.create_team('Otro equipo') as id")).id as string;
  assert.equal((await db.query('select * from public.teams where id=$1',[team])).rows.length,0);
  assert.equal((await db.query('select * from public.profiles where id=$1',[member])).rows.length,0);
  await assert.rejects(db.query('select public.join_team($1)',[crypto.randomUUID()]),/Invitación inválida/);
  await as(coach);
  const training = (await scalar("insert into public.trainings(team_id,title,starts_at) values($1,'Fondo',now()) returning id",[team])).id as string;
  await db.query("update public.trainings set title='Fondo editado' where id=$1",[training]);
  await assert.rejects(db.query('update public.trainings set team_id=$1 where id=$2',[otherTeam,training]));
  const path=`${team}/${training}/${crypto.randomUUID()}.gpx`;
  await db.query("insert into storage.objects(bucket_id,name) values('gpx',$1)",[path]);
  await db.query('insert into public.routes(training_id,team_id,path,filename) values($1,$2,$3,$4)',[training,team,path,'ruta.gpx']);
  await as(member);
  assert.equal((await db.query('select * from public.trainings')).rows.length,1);
  assert.equal((await db.query('select * from storage.objects')).rows.length,1);
  await assert.rejects(db.query("insert into public.trainings(team_id,title,starts_at) values($1,'Hack',now())",[team]),/row-level security/i);
  assert.equal((await db.query("update public.trainings set title='Hack' returning id")).rows.length,0);
  assert.equal((await db.query('delete from public.trainings returning id')).rows.length,0);
  await assert.rejects(db.query("insert into storage.objects(bucket_id,name) values('gpx',$1)",[`${team}/${training}/${crypto.randomUUID()}.gpx`]),/row-level security/i);
  assert.equal((await db.query('delete from storage.objects returning id')).rows.length,0);
  await db.query('insert into public.attendance(training_id,team_id,user_id) values($1,$2,$3)',[training,team,member]);
  await assert.rejects(db.query('insert into public.attendance(training_id,team_id,user_id) values($1,$2,$3)',[training,team,coach]),/row-level security/i);
  await assert.rejects(db.query('insert into public.attendance(training_id,team_id,user_id) values($1,$2,$3)',[training,team,member]),/duplicate key/i);
  await as(outsider);
  for(const table of ['trainings','attendance','routes']) assert.equal((await db.query(`select * from public.${table}`)).rows.length,0);
  assert.equal((await db.query('select * from storage.objects')).rows.length,0);
  await assert.rejects(db.query('insert into public.attendance(training_id,team_id,user_id) values($1,$2,$3)',[training,otherTeam,outsider]),/foreign key/i);
  await as(coach);
  assert.equal((await db.query('select * from public.attendance')).rows.length,1);
  assert.equal((await db.query('delete from public.attendance returning user_id')).rows.length,0);
  await as(member); assert.equal((await db.query('delete from public.attendance returning user_id')).rows.length,1);
  await as(admin);
  const replacement = (await scalar('select public.create_invite($1) as code',[team])).code;
  assert.notEqual(replacement,invite);
  await as(outsider); await assert.rejects(db.query('select public.join_team($1)',[invite]),/Invitación inválida/);
  await as(coach); await db.query("delete from storage.objects where name=$1",[path]); await db.query('delete from public.trainings where id=$1',[training]);
  assert.equal((await db.query('select * from public.routes')).rows.length,0);
  await db.exec('reset role; set role anon');
  await assert.rejects(db.query('select * from public.trainings'),/permission denied/i);
  await assert.rejects(db.query("select public.create_team('Hack')"),/permission denied/i);
 } finally { await db.close(); }
});
